export enum CsvHeaderColumn {
  Id = 'GUID',
  FirstName = 'First name',
  PreferredName = 'Preferred name',
  LastName = 'Last name',
  Email = 'Email',
  StartDate = 'Start date',
  EmployeeType = 'Employee type',
  OfficeLocation = 'Office Locations',
  Country = 'Country',
  Team = 'Departments',
  JobTitle = 'Job Title',
  JobTier = 'Job Tier',
  DottedLineReportsTo = 'Dotted Line Reports to',
  ReportsToJobTitle = 'Reports To Job Title',
  ReportsToFullName = 'Reports To Full Name',
  Educational = 'Educational',
  Degree = 'Degrees',
  DegreeLevel = 'Highest Grade / Degree Obtained',
}